require('plugs')
require('defaults')
require('theme')
require('lsp')
require('nerdtree')
require('devicons')
require('airline')
require('signify')
require('autocomplete')
require('test')
require('maps')

vim.cmd('autocmd BufWritePre *.rb lua vim.lsp.buf.formatting_sync(nil, 100)')
